### ISSUE TITLE
[BUG] Building Ubuntu 18 fails - cant find /install/vmlinuz

### ISSUE THREAD

**Issue by jbpoint** [vmware-samples/packer-examples-for-vsphere#145]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

21.11 (Default)

### VMware vSphere

7.0 Update 2

### HashiCorp Packer

1.7.8

### HashiCorp Packer Plugin for VMware vSphere

1.0.2

### Guest Operating System

Ubuntu Server 18.04.6

### Description

Building failes

### Expected Behavior

Building is successful

### Actual Behavior

Building failes

### Steps to Reproduce

Build

### Screenshots

![image](https://user-images.githubusercontent.com/87362739/147751491-b32eaf0d-93fb-4b35-b9e8-22dcfa0a7cf7.png)

### Additional Context

rh

**Comment by tenthirtyam** [comment]
Are the default settings of the project being used? Is the NON-LIVE .iso for Ubuntu 18 noted in the README.md being used?

Ryan

**Comment by jbpoint** [comment]
My bad.. :) 
Thank you!
