### ISSUE TITLE
when i run the build getting error below 

### ISSUE THREAD

**Issue by TouqeerHussain** [vmware-samples/packer-examples-for-vsphere#166]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

main

### VMware vSphere

6.7

### HashiCorp Packer

1.7.10

### HashiCorp Packer Plugin for VMware vSphere

1.0.3

### Guest Operating System

RHEL 7.9

### Environment Details

when i run the build getting - error creating vm: A component of the virtual machine is not accessible on the host.

### Description

Build 'vsphere-iso.linux-rhel' errored after 87 milliseconds 506 microseconds: error creating vm: A component of the virtual machine is not accessible on the host.

### Expected Behavior

Build 'vsphere-iso.linux-rhel' errored after 87 milliseconds 506 microseconds: error creating vm: A component of the virtual machine is not accessible on the host.

### Actual Behavior

Build 'vsphere-iso.linux-rhel' errored after 87 milliseconds 506 microseconds: error creating vm: A component of the virtual machine is not accessible on the host.

### Steps to Reproduce

just run the build

**Comment by tenthirtyam** [comment]
Per the README.md, the project **requires** vSphere 7.0 U2 or later for various reasons.

Your build is likely failing because the virtual hardware is still set to `19` vs one compatible with vSphere 6.7. e.g. 6.7 U2 = `15`. Note that the use of deploying EFI-based images from the content library does not work correctly and will revert to BIOS, this was addressed in vSphere 7.0 U2.

Ryan

**Comment by TouqeerHussain** [comment]
@tenthirtyam thanks for the quick reply , i have changed the both setting, but still hit by similar issue 

==> vsphere-iso.linux-rhel: Creating VM...
Build 'vsphere-iso.linux-rhel' errored after 94 milliseconds 658 microseconds: error creating vm: A component of the virtual machine is not accessible on the host.

==> Wait completed after 94 milliseconds 724 microseconds

==> Some builds didn't complete successfully and had errors:
--> vsphere-iso.linux-rhel: error creating vm: A component of the virtual machine is not accessible on the host.

==> Builds finished but no artifacts were created.

**Comment by tenthirtyam** [comment]
Per the README.md, the project **requires** vSphere 7.0 U2 or later (for various reasons.)

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/5489f31fbf422d2c1654aa58f13eeab348df8c34/README.md?plain=1#L53

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/5489f31fbf422d2c1654aa58f13eeab348df8c34/README.md?plain=1#L97-L99

Given that this environment is using 6.7, please use the [Discussions](https://github.com/vmware-samples/packer-examples-for-vsphere/discussions).

Ryan
