### ISSUE TITLE
Packer 1.8.0 on linux interprets boot_command "up" as letters "u" and "p" rather than an up-arrow kepress

### ISSUE THREAD

**Issue by bschonec** [vmware-samples/packer-examples-for-vsphere#178]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

main

### VMware vSphere

vSphere Client version 6.7.0.50000

### HashiCorp Packer

1.8.0

### HashiCorp Packer Plugin for VMware vSphere

1.0.3

### Guest Operating System

RHEL and Variants

### Description

Packer "types" in the two letters, "u" and "p" rather than interpret the intent as the up-arrow.  Changing to "<up>" solve the problem.

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/builds/linux/rocky/8/linux-rocky.pkr.hcl#L93

### Expected Behavior

When the ISO is booting and the grub/install menu is presented, the up-arrow is expected so that the kernel line can be modified.

### Actual Behavior

The two letters, "u" and "p" are sent literally.

### Steps to Reproduce

A standard packer build against centos and RHEL 8 is what I tested.

**Comment by dbond007** [comment]
The problem with that is that it is incorrect.
The up command should be
` "<up>" `
not 
`"up"`

**Comment by tenthirtyam** [comment]
I'll take care of it on my next update, but to date, it's not impacted any builds I've tested.

Please note that the project requires 7.0 U2 and higher and has not yet been updated / tested with Packer v1.8.0.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
