### ISSUE TITLE
Add support for a Debian 11 machine image

### ISSUE THREAD

**Issue by evilaliv3** [vmware-samples/packer-examples-for-vsphere#194]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Hello,

here i'm proposing the addition of a templated for Debian/Linux.

I'm already in an advanced state of creation of the configuration for the latest LTS: Debian 11

I would kindly ask your support for advancing in the configuration as i'm encountering a strange issue with the keyboard input at installation startup.

I've produced myself a complete and working boot_command that i am already using with packer+vsphere with the official packer examples, but when i plug what i developed on your work and spin up the server, after ISO boot, the boot_command seems to not be input correctly (maybe due to some keyboard misconfiguration) 

Do you have any advice that could help me debugging it futherly?

### Use Case(s)

-

### Potential Configuration

-

### References

-

**Comment by exgame** [comment]
Hello, are you able to check VMware console?

**Comment by evilaliv3** [comment]
Absolutely. In the console i see the ISO booting.

If i launch my boot_command using the official packer scripts I'm able to see the vmware console correctly issuing those and proceeding with the setup.
If i use your set of scripts instead it seems that the system is not able to issue the commands correctly. What i see is that they enter in the graphical setup and then there is keyboard input but on the wrong interfaces due to disalignment.

Please let me know if you have any advice.

I'm going to publish my current code as is so that you could see it.

**Comment by exgame** [comment]
As I can see, Debian 11 is not supported by this project. You should manually edit boot_command, for example json formated Debian 10: `"boot_command": ["<esc><wait>auto preseed/url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg<enter>"],`

**Comment by evilaliv3** [comment]
Thank you @exgame 

Let's wait for the advice by @tenthirtyam 

In the meantime here is the code that i produced: https://github.com/evilaliv3/packer-examples-for-vsphere/commit/4ac1c5fa7c80a46da52ff16f0d384b51d252d04b

**Comment by tenthirtyam** [comment]
I'll review adding Debian as a project enhancement.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Some progress made for the `disk` -based data source (non-http) using `file=dev/sr1:/ks.cfg` but there's an issue with the installer expecting a checksum `preseed_md5`(unlike http) which is rather odd.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
For now, moving from `v22.07` milestone to the `Backlog` as the cloning issue needs to be resolved for Debian 11-based OVF templates. Will still work on the outstanding gaps in the meantime.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by teadur** [comment]
https://github.com/vmware-samples/packer-examples-for-vsphere/issues/194#issuecomment-1144351281

> Some progress made for the `disk` -based data source (non-http) using `file=dev/sr1:/ks.cfg` but there's an issue with the installer expecting a checksum `preseed_md5`(unlike http) which is rather odd.
> 
> **Ryan Johnson** Staff II Solutions Architect | VMware, Inc.

Is this feature working now aswell ?

**Comment by tenthirtyam** [comment]
Per the[`CHANGELOG.md`](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/a1d82a6e7e8a494d6e88a431260429bdaf28c55e/CHANGELOG.md?plain=1#L28-L32) for the upcoming `v22.08` release,  it is HTTP-based deployment only.

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/a1d82a6e7e8a494d6e88a431260429bdaf28c55e/CHANGELOG.md?plain=1#L28-L32

Disk-based deployment planned for Debian 11 and SLES 15 when time permits for both. If you'd like to research and contribute any changes, please review the `[CONTRIBUTING.md](CONTRIBUTING.md)`.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
