### ISSUE TITLE
[BUG] Setting the `build_password` using `set-envvars.sh`

### ISSUE THREAD

**Issue by evilaliv3** [vmware-samples/packer-examples-for-vsphere#197]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

`main`

### VMware vSphere

7.0 Update 2

### HashiCorp Packer

v1.8.0

### HashiCorp Packer Plugin for VMware vSphere

v1.0.3

### Guest Operating System

Any Supported

### Environment Details

The current packer templates seem to not use the `build_password `variable so that the only password read by packer is the one that the user provides in the install script 

I've noticed this situation while working on creating a Debian template starting from the existing template for Ubuntu 18.04.

In order to fix this issue and use the `build_password` variable provided within the `set-envvars.sh` script the following instruction should be added to the templates:

```hcl
build_password = var.build_password
```

### Description

-

### Expected Behavior

-

### Actual Behavior

-

### Steps to Reproduce

Run a build setting a password `buid_password` in the config file as "password"
Run the `set-envvars.sh` script and set the password to "different_password"
Run the build.

Result: the password used by packer will be "password" and not "different_password" as expected.

### Additional Context

-

**Comment by evilaliv3** [comment]
Looking at the code i think this change shall be applied to alle the Linux distributions.

I'm instead not sure what to do for the rest of the operating systems.

**Comment by tenthirtyam** [comment]
I'll take a look at it soon and address it.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
