### ISSUE TITLE
Ansible provisioner error for Ubuntu 22.04: Could not open lock file

### ISSUE THREAD

**Issue by panzouh** [vmware-samples/packer-examples-for-vsphere#210]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

main

### VMware vSphere

6.7

### HashiCorp Packer

1.8.0

### HashiCorp Packer Plugin for VMware vSphere

1.0.4

### Guest Operating System

Ubuntu 22.04 LTS

### Environment Details

Cloned repository on a fresh Ubuntu 22.04 VM, and installed prerequisites. My Ansible is on version 6.0.0 also tried with 2.9.x.

Added `ssh_args = -o PubkeyAcceptedAlgorithms=ssh-rsa -o HostkeyAlgorithms=ssh-rsa` in ansible.cfg

### Description

The playbook is failing because it seems that it is running with the build user only (without become), I also tried to force `--become` and `--become-method=sudo` flags inside the provisioner, although they are present in `ansible/main.yml`, nothing seems to work for the first task inside `ansible/roles/base/tasks/ubuntu.yml` I get permissions denied.

### Expected Behavior

Deployment finishes successfully

### Actual Behavior

Deployment fails when updating all packages with permission denied on apt module.

### Steps to Reproduce

Clone repo
Copy config files
Start Build script :

```
packer build -force \
      --only vsphere-iso.linux-ubuntu \
      -var-file="config/vsphere.pkrvars.hcl" \
      -var-file="config/build.pkrvars.hcl" \
      -var-file="config/common.pkrvars.hcl" \
      builds/linux/ubuntu/22-04-lts
```

### Log Fragments and Files

```
"msg": "'/usr/bin/apt-get upgrade --with-new-pkgs ' failed: E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?\n",
```

Also when I connect directly to the machine the lock file is not retained by another process (checked with `lsof /var/lib/dpkg/lock-frontend`).

### Additional Context

VMWare Guest Version is 14 : https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-789C3913-1053-4850-A0F0-E29C3D32B6DA.html

**Comment by panzouh** [comment]
I added a shell command `id`, it seems that the playbook is using the `build_user` without become, output : 

```
    vsphere-iso.linux-ubuntu: TASK [base : Try id command] ***************************************************
    vsphere-iso.linux-ubuntu: task path: /home/<sensitive>/vm-templates/ansible/roles/base/tasks/ubuntu.yml:2
    vsphere-iso.linux-ubuntu: changed: [default] => {
    vsphere-iso.linux-ubuntu:     "changed": true,
    vsphere-iso.linux-ubuntu:     "cmd": "id",
    vsphere-iso.linux-ubuntu:     "delta": "0:00:00.002591",
    vsphere-iso.linux-ubuntu:     "end": "2022-06-24 10:17:39.013281",
    vsphere-iso.linux-ubuntu:     "invocation": {
    vsphere-iso.linux-ubuntu:         "module_args": {
    vsphere-iso.linux-ubuntu:             "_raw_params": "id",
    vsphere-iso.linux-ubuntu:             "_uses_shell": true,
    vsphere-iso.linux-ubuntu:             "argv": null,
    vsphere-iso.linux-ubuntu:             "chdir": null,
    vsphere-iso.linux-ubuntu:             "creates": null,
    vsphere-iso.linux-ubuntu:             "executable": null,
    vsphere-iso.linux-ubuntu:             "removes": null,
    vsphere-iso.linux-ubuntu:             "stdin": null,
    vsphere-iso.linux-ubuntu:             "stdin_add_newline": true,
    vsphere-iso.linux-ubuntu:             "strip_empty_ends": true,
    vsphere-iso.linux-ubuntu:             "warn": false
    vsphere-iso.linux-ubuntu:         }
    vsphere-iso.linux-ubuntu:     },
    vsphere-iso.linux-ubuntu:     "msg": "",
    vsphere-iso.linux-ubuntu:     "rc": 0,
    vsphere-iso.linux-ubuntu:     "start": "2022-06-24 10:17:39.010690",
    vsphere-iso.linux-ubuntu:     "stderr": "",
    vsphere-iso.linux-ubuntu:     "stderr_lines": [],
    vsphere-iso.linux-ubuntu:     "stdout": "uid=1000(<sensitive>) gid=1000(<sensitive>) groups=1000(<sensitive>),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lxd)",
    vsphere-iso.linux-ubuntu:     "stdout_lines": [
    vsphere-iso.linux-ubuntu:         "uid=1000(<sensitive>) gid=1000(<sensitive>) groups=1000(<sensitive>),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),110(lxd)"
    vsphere-iso.linux-ubuntu:     ]
    vsphere-iso.linux-ubuntu: }
```

**Comment by tenthirtyam** [comment]
**Note**: This issue is reported using an unsupported of vSphere for this project. Only vSphere 7.0.2 and above are tested.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
