### ISSUE TITLE
Allow for VM image exporting

### ISSUE THREAD

**Issue by Kennochas** [vmware-samples/packer-examples-for-vsphere#217]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

It would be nice to have a configuration option for downloading the image after it is created.

### Use Case(s)

In my use case for this, I am attempting to do the following, which is creating a completely managed content library.

(All of our code is stored inside of Azure Devops)

1. On the 15th of every month, all of the images are built by packer using CI.
2. Packer downloads the VMDK's and such using the vsphere provider exports.
3. The CI then uploads the VMDK's and associated build artifacts to ADO.
4. ADO creates a release with all of the newly updated images.
5. ADO pushes the artifacts down to a few web-servers for hosting a VMware content library.
6. Using William Lam's script (https://github.com/khensler/vmware-scripts/blob/AZBlob/python/make_vcsp_2022.py) I am creating the JSON configuration for a content library.

### Potential Configuration

In my version of the code, I am doing the following, but there may be better ways to handle it. I suspect there would be a desire to have a boolean for export or not that falls under the common variables? I am unsure of how to handle that in a packer configuration exactly.

``` yaml
 // Exporting the Template
  export {
    name = "${var.vm_guest_os_family}-${var.vm_guest_os_name}-${var.vm_guest_os_version}-${var.vm_guest_os_edition_standard}-${var.vm_guest_os_experience_core}-v${local.build_version}"
    force = true
    manifest = "sha1"
    options = ["extraconfig"]
    output_directory = "./artifacts/${var.vm_guest_os_family}-${var.vm_guest_os_name}-${var.vm_guest_os_version}-${var.vm_guest_os_edition_standard}-${var.vm_guest_os_experience_core}-v${local.build_version}"
  }

### References

https://www.packer.io/plugins/builders/vsphere/vsphere-iso#export-configuration

**Comment by tenthirtyam** [comment]
Thanks for submitting this enhancement request. I'll take this item into consideration for some of the near term updates.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
The OVF export option is pretty simple to implement from one of the common variables and the use of local variables.

I've implemented this option locally and will include this in the next release.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by tenthirtyam** [comment]
Hi, Stephen. 

I've pushed the option to the `main` branch. Give it a go before `v22.07` if you like.

You'll find the settings in the `common` variables. The export path is set to `artifacts/` currently in the locals but I plan to make that configurable.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by Kennochas** [comment]
Awesome, that's about what I figured it looked like. I was trying to see if I could figure it out myself, and wasn't too far off. Interesting the way packer has you do a for_each, even with a binary value like that.

Thank you, this along with the other ansible_user fix are enough that they let me move to your code base instead of customization's I quickly tossed in.

**Comment by tenthirtyam** [comment]
Thanks for the both the bug report and enhancement request - glad to see the updates being a help to you.

If you've not yet done so, consider starring ⭐️ the project in GitHub. It really helps.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
