### ISSUE TITLE
Add support for `iso_url` in builder configuration blocks

### ISSUE THREAD

**Issue by MarRio81** [vmware-samples/packer-examples-for-vsphere#235]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Please add support for `iso_url` in builder configuration blocks for each Linux and Windows images.

### Use Case(s)

This makes managing ISO files unnecessary. 

### Potential Configuration

TBD

### References

https://www.packer.io/plugins/builders/vsphere/vsphere-iso#iso-configuration

**Comment by tenthirtyam** [comment]
Thanks for submitting the issue. 

This enhancement is already planned, but the project will retain `iso_path` as the default configuration as not all ISOs are publicly available.
 
**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by nORKy54** [comment]
You can use the `iso_url` for local files too. It uses [go-getter](https://github.com/hashicorp/go-getter)

**Comment by tenthirtyam** [comment]
Based on further review and testing of options for #343, I will be reverting pull request https://github.com/vmware-samples/packer-examples-for-vsphere/pull/249 for this enhancement request and this project will remove support for `iso_url.`
