### ISSUE TITLE
Add support to remove NICs after image build

### ISSUE THREAD

**Issue by MarRio81** [vmware-samples/packer-examples-for-vsphere#257]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Add the ability to remove nics from vms after the Build is done.

### Use Case(s)

- Use Templates in another vCenter.
- The Ansbile vCloud Director Module has problems with existing nics in the template.

### Potential Configuration

If a condition is possible. bind this to the ovf export, because this templates are mainly used to transport other environments not having the same networks like the build en environment.

### References

https://github.com/hashicorp/packer-plugin-vsphere/issues/6

**Comment by tenthirtyam** [comment]
If I'm not mistaken, this is a requirement on the plugin to support before it can be implemented is this sample project.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
Added to backlog and labeled based on plugin dependency.

Once supported by the plugin, I’ll consider adopting the option in the project. Note however, there may be issues for OVF Templates.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
