### ISSUE TITLE
Add support for builds using static IP address assignment

### ISSUE THREAD

**Issue by tenthirtyam** [vmware-samples/packer-examples-for-vsphere#262]
### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/main/CODE_OF_CONDUCT.md).

### Community Note
- Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- Do not leave "+1" or other comments that do not add relevant information or questions.
- If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

Add support for builds using static IP address assignment.

### Use Case(s)

Provides examples for environments that are unable to use DHCP (default).

### Potential Configuration

To be determined.

There's not a native method in the [Packer Builder for VMware vSphere](https://www.packer.io/docs/builders/vsphere/vsphere-iso) to use static IP address assignment. 

Options to enable this may include:

#### Examples

**Ubuntu 18.04**

Update the ks.cfg preseed file.

```vim
# Networking
d-i netcfg/disable_autoconfig boolean true

# IPv4 Setup
d-i netcfg/get_ipaddress string <static_ipv4_address>
d-i netcfg/get_netmask string <static_ipv4_netmask>
d-i netcfg/get_gateway string <static_ipv4_gateways>
d-i netcfg/get_nameservers string <static_ipv4_dnsservers>
d-i netcfg/confirm_static boolean true
```

**Ubuntu 20.04 and later**

Update the `user-data` used by cloud-init.

```yaml
  network:
    network:
      version: 2
      ethernets:
        ens33:
         addresses: <static_ipv4_address_cidr>
         gateway4: <static_ipv4_gateway>
         nameservers:
           addresses: [<static_ipv4_dnsservers>]

```

Other Linux distributions will vary.

**Windows Server / Desktop**

Update the `autounattend.pkrtpl.hcl` with to set the IP address after the installation of VMware Tools.

```xml
         <FirstLogonCommands>
            <SynchronousCommand wcm:action="add">
               <CommandLine>%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force"</CommandLine>
               <Description>Set Execution Policy 64-Bit</Description>
               <Order>1</Order>
               <RequiresUserInput>true</RequiresUserInput>
            </SynchronousCommand>
            <SynchronousCommand wcm:action="add">
               <CommandLine>%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force"</CommandLine>
               <Description>Set Execution Policy 32-Bit</Description>
               <Order>2</Order>
               <RequiresUserInput>true</RequiresUserInput>
            </SynchronousCommand>
            <SynchronousCommand wcm:action="add">
               <CommandLine>%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -File F:\windows-vmtools.ps1</CommandLine>
               <Order>3</Order>
               <Description>Install VMware Tools</Description>
            </SynchronousCommand>
            <SynchronousCommand wcm:action="add">
               <CommandLine>%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -File F:\windows-init.ps1</CommandLine>
               <Order>4</Order>
               <Description>Initial Configuration</Description>
            </SynchronousCommand>
             <SynchronousCommand wcm:action="add">
                 <CommandLine>cmd.exe /c netsh interface ip set address "Ethernet0" static <static_ipv4_address> <static_ipv4_netmask> <static_ipv4_gateway></CommandLine>
                 <Description>Assign IP</Description>
                 <Order>5</Order>
                 <RequiresUserInput>true</RequiresUserInput>
             </SynchronousCommand>
             <SynchronousCommand wcm:action="add">
                 <CommandLine>cmd.exe /c netsh interface ip add dns "Ethernet0" <static_ipv4_dnsservers></CommandLine>
                 <Description>Assign DNS</Description>
                 <Order>6</Order>
                 <RequiresUserInput>true</RequiresUserInput>
         </FirstLogonCommands>

```

### References

None.

**Comment by jm987** [comment]
Has anyone had any success using static IP addresses instead of DHCP?   I investigated this as a possible option but was unable to get this working on Windows Server 2019 as the drivers for the network card were not loaded into WinPE and also not loaded into the Operating System. 

I also attempted unsuccessfully injecting network drivers as part of the autoattend.xml.

Thanks

**Comment by tenthirtyam** [comment]
I'll address this in a future enhancement, but I'm currently on sabbatical.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by danielhanaj** [comment]
@jm987 , we successfully utilize static IP addresses within our deployments as our networks does not have DHCP configured by default. It works as expected. The  information about static IP is part of answer file (autounattend.xml). The key here is to install VM tools before static IP can be assigned. Below FirstLogonCommands section from autounattend.xml that works for us:
```
<FirstLogonCommands>
                <SynchronousCommand wcm:action="add">
                    <Order>1</Order>
                    <CommandLine>PowerShell "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force"</CommandLine>
                    <Description>Change the default PowerShell Execution Policy from Restricted to RemoteSigned</Description>
                </SynchronousCommand>
                <SynchronousCommand wcm:action="add">
                    <Order>2</Order>
                    <CommandLine>C:\Windows\SysWOW64\cmd /c PowerShell -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force"</CommandLine>
                    <Description>Change the default PowerShell (32-bit) Execution Policy from Restricted to RemoteSigned</Description>
                </SynchronousCommand>
                <SynchronousCommand wcm:action="add">
                    <Order>3</Order>
                    <CommandLine>PowerShell -File a:\vmtools.ps1</CommandLine>
                </SynchronousCommand>
                <SynchronousCommand wcm:action="add">
                    <CommandLine>cmd.exe /c netsh interface ip set address "Ethernet0" static 192.168.1.55 255.255.255.0 192.168.1.1</CommandLine>
                    <Description>Assign static IP</Description>
                    <Order>4</Order>
                    <RequiresUserInput>true</RequiresUserInput>
                </SynchronousCommand>
                <SynchronousCommand wcm:action="add">
                    <CommandLine>cmd.exe /c netsh interface ip add dns "Ethernet0" 192.168.1.1</CommandLine>
                    <Description>Assign static DNS</Description>
                    <Order>5</Order>
                    <RequiresUserInput>true</RequiresUserInput>
                </SynchronousCommand>
                <SynchronousCommand wcm:action="add">
                    <Order>6</Order>
                    <CommandLine>PowerShell -File a:\winrm.ps1</CommandLine>
                </SynchronousCommand>
</FirstLogonCommands>
```

**Comment by jm987** [comment]
> @jm987 , we successfully utilize static IP addresses within our deployments as our networks does not have DHCP configured by default. It works as expected. The information about static IP is part of answer file (autounattend.xml). The key here is to install VM tools before static IP can be assigned. Below FirstLogonCommands section from autounattend.xml that works for us:
> 
> ```
> <FirstLogonCommands>
>                 <SynchronousCommand wcm:action="add">
>                     <Order>1</Order>
>                     <CommandLine>PowerShell "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force"</CommandLine>
>                     <Description>Change the default PowerShell Execution Policy from Restricted to RemoteSigned</Description>
>                 </SynchronousCommand>
>                 <SynchronousCommand wcm:action="add">
>                     <Order>2</Order>
>                     <CommandLine>C:\Windows\SysWOW64\cmd /c PowerShell -Command "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force"</CommandLine>
>                     <Description>Change the default PowerShell (32-bit) Execution Policy from Restricted to RemoteSigned</Description>
>                 </SynchronousCommand>
>                 <SynchronousCommand wcm:action="add">
>                     <Order>3</Order>
>                     <CommandLine>PowerShell -File a:\vmtools.ps1</CommandLine>
>                 </SynchronousCommand>
>                 <SynchronousCommand wcm:action="add">
>                     <CommandLine>cmd.exe /c netsh interface ip set address "Ethernet0" static 192.168.1.55 255.255.255.0 192.168.1.1</CommandLine>
>                     <Description>Assign static IP</Description>
>                     <Order>4</Order>
>                     <RequiresUserInput>true</RequiresUserInput>
>                 </SynchronousCommand>
>                 <SynchronousCommand wcm:action="add">
>                     <CommandLine>cmd.exe /c netsh interface ip add dns "Ethernet0" 192.168.1.1</CommandLine>
>                     <Description>Assign static DNS</Description>
>                     <Order>5</Order>
>                     <RequiresUserInput>true</RequiresUserInput>
>                 </SynchronousCommand>
>                 <SynchronousCommand wcm:action="add">
>                     <Order>6</Order>
>                     <CommandLine>PowerShell -File a:\winrm.ps1</CommandLine>
>                 </SynchronousCommand>
> </FirstLogonCommands>
> ```

This approach makes a lot of sense and thanks for sharing how you made this work.
