### ISSUE TITLE
Ansible "failed to handshake"

### ISSUE THREAD

**Issue by skupfer** [vmware-samples/packer-examples-for-vsphere#268]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

main

### VMware vSphere

7.0.3.00300

### HashiCorp Packer

1.8.3

### HashiCorp Packer Plugin for VMware vSphere

1.0.8 (linux-ubuntu.pkr.hcl)

### Guest Operating System

Ubuntu 22.04.1 LTS Server

### Environment Details

ansible 2.10.8
  config file = None
  configured module search path = ['/home/packer/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]

### Description

After seeding the vm and starting the ansible task it fails with a handshake error

### Expected Behavior

Ansible task runs

### Actual Behavior

Ansible task fails

### Steps to Reproduce

Start build.sh
Wait for ansible error

### Log Fragments and Files

```
==> vsphere-iso.linux-ubuntu: Using SSH communicator to connect: 172.23.85.129
==> vsphere-iso.linux-ubuntu: Waiting for SSH to become available...
==> vsphere-iso.linux-ubuntu: Connected to SSH!
==> vsphere-iso.linux-ubuntu: Provisioning with Ansible...
	vsphere-iso.linux-ubuntu: Setting up proxy adapter for Ansible....
==> vsphere-iso.linux-ubuntu: Executing Ansible: <sensitive>-playbook -e packer_build_name="linux-ubuntu" -e packer_builder_type=vsphere-iso -e packer_http_addr=172.23.82.32:8072 --ssh-extra-args '-o IdentitiesOnly=yes' --extra-vars display_skipped_hosts=false --extra-vars BUILD_USERNAME=<sensitive> --extra-vars BUILD_SECRET=***** --extra-vars ANSIBLE_USERNAME=<sensitive> --extra-vars ANSIBLE_SECRET=***** -e <sensitive>_ssh_private_key_file=/tmp/<sensitive>-key1568827034 -i /tmp/packer-provisioner-<sensitive>798436708 /home/packer/packer/<sensitive>/main.yml
	vsphere-iso.linux-ubuntu:
	vsphere-iso.linux-ubuntu: PLAY [all] *********************************************************************
==> vsphere-iso.linux-ubuntu: failed to handshake
	vsphere-iso.linux-ubuntu:
    vsphere-iso.linux-ubuntu: TASK [Gathering Facts] *********************************************************
	vsphere-iso.linux-ubuntu: fatal: [default]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Unable to negotiate with 127.0.0.1 port 37257: no matching host key type found. 
  Their offer: ssh-rsa", "unreachable": true}
	vsphere-iso.linux-ubuntu:
	vsphere-iso.linux-ubuntu: PLAY RECAP *********************************************************************
	vsphere-iso.linux-ubuntu: default                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
	vsphere-iso.linux-ubuntu:	
==> vsphere-iso.linux-ubuntu: Provisioning step had errors: Running the cleanup provisioner, if present...
==> vsphere-iso.linux-ubuntu: Power off VM...
==> vsphere-iso.linux-ubuntu: Destroying VM...
Build 'vsphere-iso.linux-ubuntu' errored after 8 minutes 35 seconds: Error executing Ansible: Non-zero exit status: exit status 4 
```

### Additional Context

Used  the generic pub ansible_key used later on in our playbooks. The private key is not present on the host machine since BUILD_USER should do the work, correct?

**Comment by tenthirtyam** [comment]
Please refer to the README.md and [this discussion](https://github.com/vmware-samples/packer-examples-for-vsphere/discussions/234#discussioncomment-3260695).

You may be required to update your `/etc/ssh/ssh_config` or `.ssh/ssh_config` to allow authentication with RSA keys if you are using VMware Photon OS 4.0 or Ubuntu 22.04 as the Packer host.

Update to include the following:

```vim
PubkeyAcceptedAlgorithms ssh-rsa

HostkeyAlgorithms ssh-rsa
```

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by skupfer** [comment]
This is not mentioned in the README. Might be a good idea to update it then. Didn't check the CHANGELOG.md as a first time user for this repository!

Thanks for the tip.

**Comment by tenthirtyam** [comment]
It's been added in commit https://github.com/vmware-samples/packer-examples-for-vsphere/commit/5c9cf212fc748017315b2c857b510cea60a5f600.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by tenthirtyam** [comment]
If you like the repository, pleas consider giving it a GitHub Star ⭐ - it really helps to justify some of the personal time and effort I put into the project. 😄 

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

**Comment by skupfer** [comment]
Thank you very much for your support. Very much appreciate it. Starred!
