### ISSUE TITLE
Collapse install instructions for simpler copy/paste experience

### ISSUE THREAD

**Issue by joisika** [vmware-samples/packer-examples-for-vsphere#288]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

`main`

### Motivation

Installation procedure will be easier to follow if users should run fewer commands in order to do the initial installation.

### Suggestion

Change commands to install multiple packages at once (e.g. `tdnf -y install X Y Z`).

**Comment by tenthirtyam** [comment]
Thanks for opening this tracking issue, Ivo!

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
