### ISSUE TITLE
Add support for alternative language for Windows local admin

### ISSUE THREAD

**Issue by matteu31400** [vmware-samples/packer-examples-for-vsphere#332]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

When you use packer on a non en-us system, there are some error 

I have to replace some content on scripts\windows\windows-prepare.ps1

Set-LocalUser -name Administrator -PasswordNeverExpires $true
to
$AdministratorAccount = (Get-LocalUser | where {$_.sid -like "*-500"}).name
Set-LocalUser -name $AdministratorAccount -PasswordNeverExpires $true

### Use Case(s)

I test it for W2019 datacenter templates

### Potential Configuration

nothing special

**Comment by tenthirtyam** [comment]
**Use Case**:

The local administrator account is not always named Administrator in localized versions of the Windows operating system. For example, it could be Järjestelmänvalvoja, Administrateur, Rendszergazda, Administrador, Администратор, Administrador or Administratör.

```PowerShell
$localAdministrator = (Get-LocalUser | Where-Object {$_.sid -like "*-500"}).name

Set-LocalUser -name $localAdministrator -PasswordNeverExpires $true
```

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.
