### ISSUE TITLE
Add support for alternative language for Windows remote desktop firewall

### ISSUE THREAD

**Issue by matteu31400** [vmware-samples/packer-examples-for-vsphere#333]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

On Windows system, when language is not english, FW for remote desktop are not enabled because the rule name is linked to english.
On file scripts\windows\windows-prepare.ps1

I replace Enable-NetFirewallRule -DisplayGroupName "Remote desktop"
to
Enable-NetFirewallRule -Group "@FirewallAPI.dll,-28752"

### Use Case(s)

other language than english

### Potential Configuration

nothing special

**Comment by tenthirtyam** [comment]
Reference: [Microsoft Documentation](https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/networking-mpssvc-svc-firewallgroups-firewallgroup)
