### ISSUE TITLE
Add support for Photon OS 5.0

### ISSUE THREAD

**Issue by lamw** [vmware-samples/packer-examples-for-vsphere#470]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

It would be useful to include an example for the latest VMware Photon OS 5.0 (_currently in beta_) which was just launched 2023-01-30.

### Use Case(s)

Custom Virtual Appliance 

### Potential Configuration

TBD

### References

https://github.com/vmware/photon/wiki/What-is-New-in-Photon-OS-5.0

**Comment by tenthirtyam** [comment]
Thanks for adding this, William. I just noticed yesterday!

**Comment by tenthirtyam** [comment]
Looking forward to support for `fs_options` that I'd requested. https://github.com/vmware/photon-os-installer/commit/5783fb9d549d55f8512b17562d7a52a6b2575d0d.

**Comment by tenthirtyam** [comment]
Will look at this one once https://github.com/vmware-samples/packer-examples-for-vsphere/pull/473 is merged.

**Comment by tenthirtyam** [comment]
Now GA: https://github.com/vmware/photon/wiki/Downloading-Photon-OS#downloading-photon-os-50-ga
