### ISSUE TITLE
.gitignore is incomplete

### ISSUE THREAD

**Issue by tintinhamans** [vmware-samples/packer-examples-for-vsphere#472]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

23.01 (latest)

### VMware vSphere

7.0.3j

### HashiCorp Packer

1.8.5

### HashiCorp Packer Plugin for VMware vSphere

1.1.1

### Guest Operating System

Photon OS 4.0

### Description

The current `.gitignore` file fails to ignore exported artifacts as intended and it also doesn't exclude `tfplan` files from Terraform which could contain sensitive information.

### Expected Behavior

1. `.vmdk`, `.nvram`, `.ovf` and `.mf` files in the `artifacts` directory should be ignored as I assume this is supposed to do:

```
# Artifacts
## Ignore artifacts directory.
artifacts/*.mf
artifacts/*.nvram
artifacts/*.ovf
artifacts/*.vmdk
```
2.  `tfplan` files should also be ignored.

### Actual Behavior

1. `.vmdk`, `.nvram`, `.ovf` and `.mf` in the `artifacts` directory are not being ignored as I assume was originally intended.
2. `tfplan` files are currently not being ignored in .gitignore. Since these may contain sensitive information I think this should be added.

### Steps to Reproduce

1. Running any build with ovf export enabled should produce artifacts in the `artifacts` directory:
```hcl
// OVF Export Settings
common_ovf_export_enabled   = true
```

These are not correctly being ignored
```
$ git ls-files --exclude-standard --others
artifacts/linux-ubuntu-22.04-lts-v23.01/linux-ubuntu-22.04-lts-v23.01-0.vmdk
artifacts/linux-ubuntu-22.04-lts-v23.01/linux-ubuntu-22.04-lts-v23.01.mf
artifacts/linux-ubuntu-22.04-lts-v23.01/linux-ubuntu-22.04-lts-v23.01.ovf
```

2. Running a `terraform plan` should produce a `tfplan` file, this is not being ignored presently:
```
$ git ls-files --exclude-standard --others
terraform/vsphere-role/tfplan
```

**Comment by tenthirtyam** [comment]
Please feel free to submit a pull request for the enhancement.
