### ISSUE TITLE
`boot_command` comments explaining key presses

### ISSUE THREAD

**Issue by natedogith1** [vmware-samples/packer-examples-for-vsphere#656]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

main

### Motivation

Currently the boot_command is an opaque list of keys, it's hard to figure out what it's doing without comments, especially if it's failing.

For instance, sles 15 has this
```hcl
  boot_command = [
    "<esc>",
    "e",
    "<down><down><down><down><end>",
    "${local.data_source_command}",
    "<f10>"
  ]
```

I have no idea what what `"<esc>"` and `"e"` are trying to accomplish. ` "<down><down><down><down><end>"` is presumably navigating to some text box to modify the kernel command line, given the contents of `local.data_source_command`.  I assume `"<f10>"` is a hotkey for starting the installation, since it's the last entry.

### Suggestion

Comments should be added to explain what each key sequence is accomplishing (what menu option is being selected, what action a hotkey performs, etc).

**Comment by tenthirtyam** [comment]
These are specific to the OS and the data source used.

Added to the backlog for future consideration.
