### ISSUE TITLE
Debian 12 ready (and documented) but no tag updated

### ISSUE THREAD

**Issue by necarnot** [vmware-samples/packer-examples-for-vsphere#660]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

main

### VMware vSphere

7.0.3d

### HashiCorp Packer

1.9.1

### HashiCorp Packer Plugin for VMware vSphere

1.2.0

### Guest Operating System

Ubuntu 22.04

### Description

The README.md reads Debian 12 is supported, and the relevant commit has been merged into main.
But no new TAG has been updated since 2023-01-17 though many improvements are worth publishing.

### Expected Behavior

Strictly follows the README.md and be able to produce a Debian 12 template.

### Actual Behavior

The present 23.01 tag does not include latest commit, including those allowing to produce a Debian 12 template

### Steps to Reproduce

Just follow the doc...

**Comment by tenthirtyam** [comment]
Hi! I will be in the next release milestone. Please refer to the changelog.

**Comment by tenthirtyam** [comment]
Switched to `develop` branch. 

`main` now aligns with the lastest release.
