### ISSUE TITLE
Add support to dynamically customize Linux package selections

### ISSUE THREAD

**Issue by tenthirtyam** [vmware-samples/packer-examples-for-vsphere#694]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Add support to dynamically customize Linux package selections beyond the base defaults.

### Use Case(s)

Provide the ability to generate more specific builds without kickstart modifications.

### Potential Configuration

To be determined.

**Comment by sestegra** [comment]
@tenthirtyam Please assign it to me.
It's similar to https://github.com/vmware-samples/packer-examples-for-vsphere/pull/473
Before starting, I would need the merge of this PR.
