### ISSUE TITLE
ISO Properly configured but not connected

### ISSUE THREAD

**Issue by clementcohen** [vmware-samples/packer-examples-for-vsphere#721]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

latest

### VMware vSphere

8.0.0.10000

### HashiCorp Packer

1.9.4

### HashiCorp Packer Plugin for VMware vSphere

packer-plugin-vsphere_v1.2.1_x5.0_darwin_arm64

### Guest Operating System

Ubuntu Server 22.04 LTS

### Environment Details

Macbook PRO M1 ( Sonoma) 

### Description

The ISO datastore is not connected (checkbox is not ticked) to the VM  so the process didn't go through

### Expected Behavior

Datastore conencted checkbox ticked

### Actual Behavior

checkbox not ticked so  ISO Not connected

### Steps to Reproduce

./config.sh  tpl-2204
./build.sh tpl-2204  choice 5 

### Log Fragments and Files

```sh
CONFIRM: Build a Ubuntu Server 22.04 LTS (cloud-init) Template for VMware vSphere?

Continue? (y/n)
y
Building a Ubuntu Server 22.04 LTS (cloud-init) Template for VMware vSphere...
Initializing HashiCorp Packer and required plugins...
Starting the build....
packer build -force -on-error=ask 
Warning: Bundled plugins used

This template relies on the use of plugins bundled into the Packer binary.
The practice of bundling external plugins into Packer will be removed in an
upcoming version.

To remove this warning, add the following section to your template:

packer {
  required_plugins {
    vsphere = {
      source  = "github.com/hashicorp/vsphere"
      version = "~> 1"
    }
    <sensitive> = {
      source  = "github.com/hashicorp/<sensitive>"
      version = "~> 1"
    }
  }
}

Then run 'packer init' to manage installation of the plugins


vsphere-iso.linux-<sensitive>: output will be in this color.

==> vsphere-iso.linux-<sensitive>: Creating VM...
==> vsphere-iso.linux-<sensitive>: Customizing hardware...
==> vsphere-iso.linux-<sensitive>: Adding SATA controller...
==> vsphere-iso.linux-<sensitive>: Mounting ISO images...
==> vsphere-iso.linux-<sensitive>: Adding configuration parameters...
==> vsphere-iso.linux-<sensitive>: Starting HTTP server on port 8078
==> vsphere-iso.linux-<sensitive>: Set boot order...
==> vsphere-iso.linux-<sensitive>: Power on VM...
==> vsphere-iso.linux-<sensitive>: Waiting 5s for boot...
==> vsphere-iso.linux-<sensitive>: HTTP server is working at http://192.168.20.176:8078/
==> vsphere-iso.linux-<sensitive>: Typing boot command...
==> vsphere-iso.linux-<sensitive>: Waiting for IP...
Cancelling build after receiving interrupt
==> vsphere-iso.linux-<sensitive>: Step "StepWaitForIp" failed
==> vsphere-iso.linux-ubuntu: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)? c
==> vsphere-iso.linux-<sensitive>: Power off VM...
==> vsphere-iso.linux-<sensitive>: Destroying VM...
    vsphere-iso.linux-<sensitive>: Closing sessions ....
Build 'vsphere-iso.linux-<sensitive>' errored after 17 minutes 11 seconds: context canceled
```

### Screenshots

[![Capture-d-e-cran-2023-10-03-a-22-00-48.png](https://i.postimg.cc/HW83jptB/Capture-d-e-cran-2023-10-03-a-22-00-48.png)](https://postimg.cc/fkZYrQp9)

### Additional Context

Try from  tarball  v23.01 and develop  branch : same issue 
no error. has been  shown on vsphere side nor packer 
the file in ISOs datastore exist and location is OK

**Comment by clementcohen** [comment]
looks like packer use  some plugins  bundled with  packer binary 
not sure how to fix  cauz  it's already  there  in  builds/linux/ubuntu/22-04-lts/linux-ubuntu.pkr.hcl. file

**Comment by tenthirtyam** [comment]
File name on the datastore and in the `linux-ubuntu.auto.pkrvars.hcl`?

For the `develop` branch it's `ubuntu-22.04.3-live-server-amd64.iso`.

**Comment by clementcohen** [comment]
Yes i update  the file accordingly 
I’ve found the issue permission on my iso datastore 
Issue are  solved now thanks :))
