### ISSUE TITLE
Add support for Ubuntu 23.10

### ISSUE THREAD

**Issue by lamw** [vmware-samples/packer-examples-for-vsphere#725]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Ubuntu 23.10 (https://releases.ubuntu.com/23.10/) was just released, would be good to include 

### Use Case(s)

Using newer releases of Ubuntu

### Potential Configuration

TBD

**Comment by tenthirtyam** [comment]
I usually wait for LTS but will consider this one! 😉

**Comment by sopleb** [comment]
23.04 LTS is out, should probably add that one
