### ISSUE TITLE
No explanation of build_password_encrypted and build_key

### ISSUE THREAD

**Issue by levensailor** [vmware-samples/packer-examples-for-vsphere#747]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### Motivation

I have a build failing while executing the ansible tasks and i'm sure it has to do with the values of build_password_encrypted and/or build_key. 

I would like an explanation on how to obtain the values. I'm guessing the build_key is my public rsa key on my mac but unsure and unsure how the vm would have that baked in. the encrypted password i have no idea how its encrypted

### Suggestion

Please explain in the documentation how to obtain these values and how they are used in the build.

**Comment by tenthirtyam** [comment]
This is documented [here](https://vmware-samples.github.io/packer-examples-for-vsphere/getting-started/configuration/#configuration-variables).

You need to generate both and update `config/build.pkrvars.hcl`.
