### ISSUE TITLE
No network after build

### ISSUE THREAD

**Issue by arkadicolson** [vmware-samples/packer-examples-for-vsphere#775]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

latest

### VMware vSphere

7.0.3.01700

### HashiCorp Packer

1.9.4

### HashiCorp Packer Plugin for VMware vSphere

1.2.2

### Guest Operating System

Ubuntu Server 22.04 LTS

### Environment Details

Packer is running on a debian machine. Trying to build ubuntu 22

### Description

When the machine boots I see that /etc/machine-id has permission 0000. So the network daemon is unable to start and no netwerk is there... Somebody an idea why? It has something to do with the code below...

# Tasks to clean the machine-id.
- name: "Cleaning the machine-id."
  block:
    - name: "Resizing the /etc/machine-id."
      file:
        path: /etc/machine-id
        state: touch
        mode: '0000'
    - name: "Removing /var/lib/dbus/machine-id."
      file:
        path: /var/lib/dbus/machine-id
        state: absent
    - name: "Creating a symbolic link to /etc/machine-id."
      file:
        src: /etc/machine-id
        dest: /var/lib/dbus/machine-id
        state: link

### Expected Behavior

Network is there after booting the created vm

### Actual Behavior

No network is there after booting the created vm

### Steps to Reproduce

Just build with number 6

**Comment by tenthirtyam** [comment]
I using the latest from develop branch versus a release there are chances to pick up issues. :) 

This was resolved last evening in https://github.com/vmware-samples/packer-examples-for-vsphere/pull/774 as a result from the switch to dedicated modules.
