### ISSUE TITLE
Debian 12 disk based deployement not working

### ISSUE THREAD

**Issue by spawn451** [vmware-samples/packer-examples-for-vsphere#786]
Sorry, but not sure to understand but yes it is based on datasource selection.

My datasource content and command look like this:
```
  data_source_content = {
    "/preseed.cfg" = templatefile("${abspath(path.root)}/data/preseed.pkrtpl.hcl", {
      build_username           = var.build_username
      build_password_encrypted = var.build_password_encrypted
      build_public_key         = var.build_public_key
      vm_guest_os_language     = var.vm_guest_os_language
      vm_guest_os_keyboard     = var.vm_guest_os_keyboard
      vm_guest_os_timezone     = var.vm_guest_os_timezone
    })
  }
  
  data_source_command = var.common_data_source == "http" ? "url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/preseed.cfg" : "file=/media/preseed.cfg"
  ```
I need to use the `cd_content` variable instead of `floppy_content` like this:
```
 cd_content = var.common_data_source == "disk" ? local.data_source_content : null
 ```

The `http_content` is like other template:
```
http_content   = var.common_data_source == "http" ? local.data_source_content : null
```

And my `boot_command` look like this:
```
  boot_command = [
    "<wait3s>c<wait3s>",
    "linux /install.amd/vmlinuz",
    " auto=true priority=critical locale=${var.vm_guest_os_language}",
    " debconf/frontend=noninteractive",
    " ${local.data_source_command}<enter>",
    "initrd /install.amd/initrd.gz<enter>",
    "boot<enter>",
    "<wait30s>",
    "<enter><wait>",
    "<enter><wait>",
    "<leftAltOn><f2><leftAltOff>",
    "<enter><wait>",
    "mount /dev/sr1 /media<enter>",
    "<leftAltOn><f1><leftAltOff>",
    "<down><down><down><down><enter>"
  ]
``` 

I can not use the `http` content source in my project due to firewall segmentation, so my `common_data_source` variable is set to `disk` in my common variable file `common_pkrvars.hcl`.

```
common_data_source      = "disk"
```

And it works like this.

_Originally posted by @ukushisanet in https://github.com/vmware-samples/packer-examples-for-vsphere/issues/261#issuecomment-1251536186_

**Comment by spawn451** [comment]
Hello, I tried this but cannot make it work.
![image](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/87195479/d873e735-4f49-470e-88ec-c084efacd522)
Any idea ?

**Comment by tenthirtyam** [comment]
Please open an issue using the correct issue for with all the requested details.
