### ISSUE TITLE
Debian 12 disk-based deployment not working

### ISSUE THREAD

**Issue by spawn451** [vmware-samples/packer-examples-for-vsphere#787]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

latest

### VMware vSphere

vCenter 8.0.2 -  ESXi, 8.0.0, 21203435

### HashiCorp Packer

1.9.4

### HashiCorp Packer Plugin for VMware vSphere

1.2.2

### Guest Operating System

Windows 10 Professional 22H2

### Environment Details

Packer is running on a Windows 10 machine. Trying to build Debian 12 with disk-based deployement.

### Description

Following issue #261 I'm trying to build Debian 12 with disk-based deployement but It is not working.

### Expected Behavior

Debian 12 should build without issues using disk-based deployment

### Actual Behavior

When starting the installation I get the following error :
**Failed to retrieve the preconfiguration file**
The file needed for preconfiguration could not be retrieved from file:///media/ks.cfg.
The installation will proceed in non-automated mode.

I can see on the VM that the two CD-ROM are correctly mounted.

### Steps to Reproduce

  Bellow the code used :
```bash
common_data_source = "disk"
```
```bash
data_source_content = {
    "/ks.cfg" = templatefile("${abspath(path.root)}/data/ks.pkrtpl.hcl", {
      build_username           = local.build_username
      build_password_encrypted = local.build_password_encrypted
      vm_guest_os_language     = var.vm_guest_os_language
      vm_guest_os_keyboard     = var.vm_guest_os_keyboard
      vm_guest_os_timezone     = var.vm_guest_os_timezone
      common_data_source       = var.common_data_source
    })
  }
  data_source_command = var.common_data_source == "http" ? "url=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg" : "file=/media/ks.cfg"
  mount_cdrom_command = "<leftAltOn><f2><leftAltOff> <enter><wait> mount /dev/sr1 /media <enter> <leftAltOn><f1><leftAltOff>"
  mount_cdrom         = var.common_data_source == "http" ? " " : local.mount_cdrom_command
```
```bash
cd_content   = var.common_data_source == "disk" ? local.data_source_content : null
```
```bash
  boot_command = [
    "<wait3s>c<wait3s>",
    "linux /install.amd/vmlinuz",
    " auto-install/enable=true",
    " debconf/priority=critical",
    " ${local.data_source_command}",
    " noprompt --<enter>",
    "initrd /install.amd/initrd.gz<enter>",
    "boot<enter>",
    "<wait30s>",
    "<enter><wait>",
    "<enter><wait>",
    " ${local.mount_cdrom}",
    "<down><down><down><down><enter>"
  ]
```

### Screenshots

![image](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/87195479/4c6417e0-b84b-45d5-a526-8c832a40680e)
![image](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/87195479/5f33125a-06ab-4498-b0cc-693a5a69e38a)
![image](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/87195479/b226026b-6eda-4d03-b119-1fcaadb3092a)

**Comment by tenthirtyam** [comment]
I should be able to take a look at it tomorrow. Can you confirm that you let it sit for a bit? It should error and then pick up after the mount of sr1.

**Comment by spawn451** [comment]
I let it sit for a bit as you suggested, it is working :) Thanks!

**Comment by tenthirtyam** [comment]
Thank you for confirming.

There is a wait period for the media to be mounted if the disk base path is set. Debian was a little tricky.
