### ISSUE TITLE
Add support for an option to use a content library for ISOs

### ISSUE THREAD

**Issue by akulbe** [vmware-samples/packer-examples-for-vsphere#807]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Since you can download ISO files direct to a Content Library now, it would be _great_ to have the ability to point to a Content Library for the ISO files, rather than requiring them to be in a datastore with a specific path required.

### Use Case(s)

Since you can download ISO files direct to a Content Library now, it would be _great_ to have the ability to point to a Content Library for the ISO files, rather than requiring them to be in a datastore with a specific path required.

### Potential Configuration

.

**Comment by tenthirtyam** [comment]
I added this option this evening in my environment and it works well.

```shell
2024/03/28 03:08:16 ui: ==> vsphere-iso.linux-photon: Adding SATA controller...
2024/03/28 03:08:16 ui: ==> vsphere-iso.linux-photon: Adding CD-ROM device...
2024/03/28 03:08:16 packer-plugin-vsphere_v1.2.4_x5.0_linux_amd64 plugin: 2024/03/28 03:08:16 Check if ISO path is a Content Library path
2024/03/28 03:08:16 packer-plugin-vsphere_v1.2.4_x5.0_linux_amd64 plugin: 2024/03/28 03:08:16 ISO path identified as a Content Library path
2024/03/28 03:08:16 packer-plugin-vsphere_v1.2.4_x5.0_linux_amd64 plugin: 2024/03/28 03:08:16 Finding the equivalent datastore path for the Content Library ISO file path
2024/03/28 03:08:17 packer-plugin-vsphere_v1.2.4_x5.0_linux_amd64 plugin: 2024/03/28 03:08:17 Creating CD-ROM on controller '&{{{} 15000 0xc000feb360 <nil> <nil> <nil> 100 0xc000bdd0d8 0 <nil>} 0 []}' with iso '[local-ssd-01] contentlib-a0d5b9f6-b1c4-45f9-95c2-4dfd25d6f0e5/0a8ce2e8-1f62-4e36-956f-c499003d99ec/photon-4.0-c001795b8_7349277a-45a7-4d3a-a25f-7b2241289442.iso'
```

Just need to do some housekeeping and see if I like the implementation ease to toggle between datastore and content library.

It's good timing because I was working on some updates in the plugin too. :)

Ryan
