### ISSUE TITLE
VMs deployed of Debian 12.4 templates do not boot up with network device connected.

### ISSUE THREAD

**Issue by slekkus75** [vmware-samples/packer-examples-for-vsphere#848]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Hi, I am trying to deploy the debian template with Ansible using the vmware community collection but have not been able to get the VM booting up with the network interface in a connected state. I am using vsphere 7.03 (which should support debian 12 guest customization, using "other5xLinux64Guest"). I just saw an identical issue using terraform, which is solved. I use the latest devel branch which injects other5xLinux64Guest into /etc/vmware-tools/tools.conf. Have also tried many other tips I found, like: guestinfo variants, starting dbus before vm-tools and what not - all didn't help.

### Use Case(s)

na

### Potential Configuration

na

### References

na

**Comment by tenthirtyam** [comment]
Same with Debian 11?

**Comment by slekkus75** [comment]
> Same with Debian 11?

Yes, just tested it with debian 11.9, same result. Not sure what it is but this seems to be an old issue with vmware (tools). 
Been testing various settings in tools.conf and what not, no success. Going to try cloud-init for debian.

**Comment by tenthirtyam** [comment]
How long did you let it settle for after guest customization?

**Comment by slekkus75** [comment]
around one minute. I will do some new tests tomorrow and let it settle a little longer.

**Comment by slekkus75** [comment]
Tried to let it settle for about 45 minutes. interface doesn't come up.
Just went with cloud-init for the debian template, which works. Not sure if other6xLinux64Guest should work on vsphere  8, suspect it will. For me cloud-init is the solution for now. Might as well close this issue.
