### ISSUE TITLE
can't mount centos 7 iso 

### ISSUE THREAD

**Issue by halinwu** [vmware-samples/packer-examples-for-vsphere#856]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### VMware vSphere

8.0.2

### HashiCorp Packer

1.10.1

### HashiCorp Packer Plugin for VMware vSphere

1.2.1

### Guest Operating System

ubuntu 22.04

### Environment Details

I download [packer-examples-for-vsphere frome github , the version is 23.11.  please refer my environment  just like above infos. 

### Description

I could generate rocky9/photon5 template , but when I build centos7 template , I can't mount centos 7 iso file, even I change firmware as bios, it couldn't work.  please refer to the HCI config file 
![Pasted Graphic 2](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/34537132/936dfa39-9d45-413e-9fb0-25db7d84dbe1)
the packer processing 
![Pasted Graphic 3](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/34537132/cd8d7e22-d579-4102-9feb-00c166f9c50e)
the centos prepare  during  installation
![Pasted Graphic](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/34537132/2384c3a6-8e0b-4eea-9827-a45b570d6de8)

### Expected Behavior

build up the centos 7 template like the other linux os 

### Actual Behavior

can't mount iso file ,so it couldn't install automatically

### Steps to Reproduce

please check my configure file, could you tell me how to change those parameters ?

**Comment by tenthirtyam** [comment]
The project does not yet add support for using the ISO from the content library but there is an open enhancement I have planned for. See #807.

**Comment by halinwu** [comment]
I found the problem , I set  the firmware as efi , it colud be work.
