### ISSUE TITLE
Add Fedora Server Linux distribution

### ISSUE THREAD

**Issue by JM2K69** [vmware-samples/packer-examples-for-vsphere#885]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Description

Would it be possible to add the Fedora Server distribution to the project. It is a distribution that is also widely used.

### Use Case(s)

A new distribution.

### Potential Configuration

I have already carried out tests, it seems to work except the Ansible part which gives me an error. I used Almalinux 9 as a model.

**Comment by JM2K69** [comment]
Here the error for ansible
![image](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/17923944/a690cb23-78ef-4f26-80cf-5f07f9ab5b91)

**Comment by tenthirtyam** [comment]
Try:

```hcl 

ansible_env_vars = [
    "ANSIBLE_CONFIG=${path.cwd}/ansible/ansible.cfg",
    "ANSIBLE_PYTHON_INTERPRETER=/usr/bin/python3"
]

```

**Comment by tenthirtyam** [comment]
You'd need to update https://github.com/vmware-samples/packer-examples-for-vsphere/blob/develop/ansible/roles/base/tasks/main.yml if it does not detect it under the RedHat OS family.

**Comment by tenthirtyam** [comment]
In progress.

**Comment by JM2K69** [comment]
I will test it now.

**Comment by burnsjared0415** [comment]
approve
