### ISSUE TITLE
Correct a typo in builds/linux/ubuntu/24-04-lts/data/user-data.pkrtpl.hc

### ISSUE THREAD

**Issue by robertzakrocki** [vmware-samples/packer-examples-for-vsphere#914]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### Motivation

There is a typo in builds/linux/ubuntu/24-04-lts/data/user-data.pkrtpl.hc file, Ubuntu Server *34.04* LTS it should be Ubuntu Server *24.04* LTS.

I've created a pull request for this but not sure if you are accepting cosmetic changes... here it is: https://github.com/vmware-samples/packer-examples-for-vsphere/pull/913

**Comment by tenthirtyam** [comment]
Resolved in [044eb95](https://github.com/vmware-samples/packer-examples-for-vsphere/commit/044eb950d6f87e8ea866fe6ab61bb64f66891b2e).
