### ISSUE TITLE
Add variable validation for build user case and length

### ISSUE THREAD

**Issue by JM2K69** [vmware-samples/packer-examples-for-vsphere#915]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### VMware vSphere

7.0.3

### HashiCorp Packer

1.10.3

### HashiCorp Packer Plugin for VMware vSphere

1.26.7

### Guest Operating System

Debian 12.5

### Description

Error when username start with un Upercase : I use **User**. 

### Expected Behavior

the build must continue

### Actual Behavior

the build stop

### Steps to Reproduce

Use a username for exemple Packer the build will fail with debian 12;5

### Screenshots

![image](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/17923944/1b22575c-608c-43e8-9384-31901fedd006)

**Comment by tenthirtyam** [comment]
This would likely impact more than just Debian 12. Certainly Debian 11 and other Linux distributions.

**Comment by tenthirtyam** [comment]
I've updated the issue description to reflect the changes needed.

**Comment by JM2K69** [comment]
I try this regex validation without success @tenthirtyam 
```
variable "build_username" {
  type        = string
  description = "The username to login to the guest operating system
  validation {
       condition     = can(regex("^[a-z][a-zA-Z0-9_]*", var.build_username))
    error_message = "The username account must start with a letter in lowercase"
  }
 validation {
    condition     = length(var.build_username) > 4 && length(var.build_username) < 8
    error_message = "The username lenght must between 4 and 8 characters"
  }
}
```

**Comment by tenthirtyam** [comment]
We have a PR in with a change that will address this requirement when using an updated build script.

**Comment by JM2K69** [comment]
> We have a PR in with a change that will address this requirement when using an updated build script.
Should we close this issue ? And start a new one ?

**Comment by tenthirtyam** [comment]
Nah, all good. This issue is linked to the PR.
