### ISSUE TITLE
WinRM Operation Timeout

### ISSUE THREAD

**Issue by Sportcast-DE** [vmware-samples/packer-examples-for-vsphere#917]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

latest

### VMware vSphere

vcenter 8.0.2 Build:23504390 esxi: VMware ESXi, 8.0.2, 23305546

### HashiCorp Packer

HashiCorp Packer 1.10.3

### HashiCorp Packer Plugin for VMware vSphere

latest

### Guest Operating System

Ubuntu 22.04.4 LTS

### Description

During the Build process after the Ansible Task "Installing additional packages using Chocolatey" the build process stops and the only choice is to cancel the Build Process. The error message is the Following Meessage:
vsphere-iso.windows-server-datacenter-core: [WARNING]: ERROR DURING WINRM SEND INPUT - attempting to recover:
    vsphere-iso.windows-server-datacenter-core: WinRMOperationTimeoutError
    vsphere-iso.windows-server-datacenter-dexp: [WARNING]: ERROR DURING WINRM SEND INPUT - attempting to recover:
    vsphere-iso.windows-server-datacenter-dexp: WinRMOperationTimeoutError

### Expected Behavior

The Ansible Task should install additional packages with Chocolatey

### Actual Behavior

The Build Process runs in an Timeout

### Steps to Reproduce

Start a Build Process with Ansible 2.15.0 

### Additional Context

The WinRm Time out is a know issue: https://github.com/ansible-collections/ansible.windows/issues/516
After update from Ansible 2.15 to 2.15.5 the build process doesnt throw this message again.

**Comment by tenthirtyam** [comment]
See https://github.com/vmware-samples/packer-examples-for-vsphere/discussions/912.

This would be documentation update for a dependency.

**Comment by Sportcast-DE** [comment]
Thx. I didnt saw this entry.
