### ISSUE TITLE
Syntax error in one of the Linux ansible playbook

### ISSUE THREAD

**Issue by robertzakrocki** [vmware-samples/packer-examples-for-vsphere#922]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### VMware vSphere

7.0.3

### HashiCorp Packer

1.10.3

### HashiCorp Packer Plugin for VMware vSphere

1.2.7

### Guest Operating System

Ubuntu Server 24.04LTS

### Description

Packer fails linux vm builds because of a syntax error in one of the ansible playbook files. The error comes from packer-examples-for-vsphere/ansible/roles/base/tasks/linux.yml file.

### Expected Behavior

Ansible successfully executes packer-examples-for-vsphere/ansible/roles/base/tasks/linux.yml playbook

### Actual Behavior

Packer fails with the following error:
    vsphere-iso.linux-ubuntu: ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
    vsphere-iso.linux-ubuntu: TASK [base : Update the operating system and install additional packages.] *****
    vsphere-iso.linux-ubuntu: JSON: Expecting value: line 1 column 1 (char 0)
    vsphere-iso.linux-ubuntu:
    vsphere-iso.linux-ubuntu: Syntax Error while loading YAML.
    vsphere-iso.linux-ubuntu:   did not find expected key
    vsphere-iso.linux-ubuntu:
    vsphere-iso.linux-ubuntu: The error appears to be in '/***********/<sensitive>-examples-for-vsphere/<sensitive>/roles/base/tasks/linux.yml': line 127, column 3, but may
    vsphere-iso.linux-ubuntu: be elsewhere in the file depending on the exact syntax problem.
    vsphere-iso.linux-ubuntu:
    vsphere-iso.linux-ubuntu: The offending line appears to be:
    vsphere-iso.linux-ubuntu:
    vsphere-iso.linux-ubuntu:
    vsphere-iso.linux-ubuntu:   - name: "Installing cloud-init."
    vsphere-iso.linux-ubuntu:   ^ here
==> vsphere-iso.linux-ubuntu: Error executing Ansible: Non-zero exit status: exit status 4
==> vsphere-iso.linux-ubuntu: Step "StepProvision" failed

### Steps to Reproduce

Attempt to build/rebuild a linux template using packer

### Screenshots

![Screenshot 2024-05-13 at 10 54 03](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/58635806/26e82014-649a-4270-a9e8-97127420cf36)

**Comment by tenthirtyam** [comment]
@burnsjared0415 can you take a look at this? I think it's related to the update for SLES last Friday.

**Comment by tenthirtyam** [comment]
@robertzakrocki Please pull the latest from `develop` and try again.

**Comment by robertzakrocki** [comment]
Many thanks @tenthirtyam, the issue is now fixed. Ansible finishes as expected.

**Comment by tenthirtyam** [comment]
Thank you for confirming!
