### ISSUE TITLE
develop: Error ansible with RHEL 9.3

### ISSUE THREAD

**Issue by JM2K69** [vmware-samples/packer-examples-for-vsphere#929]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### VMware vSphere

7.0.3

### HashiCorp Packer

1.10.3

### HashiCorp Packer Plugin for VMware vSphere

1.26.7

### Guest Operating System

RHEL 9.3

### Description

The Ansible Gather task failed with Msg "Missing sudo password"

### Expected Behavior

The ansible task need to find all OS Informations

### Actual Behavior

The steps failed

### Steps to Reproduce

Clone de develop branch and launch a build

### Screenshots

![image](https://github.com/vmware-samples/packer-examples-for-vsphere/assets/17923944/54717bc9-b7e9-4cdb-aa0f-ca56660003e7)

**Comment by tenthirtyam** [comment]
It's known and is already being addressed for the release.
