### ISSUE TITLE
There is a line of comment repeated in 'builds/linux/ubuntu-20-04-lts/data/user-data.pkrtpl.hcl'

### ISSUE THREAD

**Issue by sepsh** [vmware-samples/packer-examples-for-vsphere#937]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### Motivation

There is a typo in

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/d2fde04a56867801bdaeb550e8aed3bf8e62af3f/builds/linux/ubuntu/20-04-lts/data/user-data.pkrtpl.hcl#L4

as it is probably copy pasted from 

https://github.com/vmware-samples/packer-examples-for-vsphere/blob/d2fde04a56867801bdaeb550e8aed3bf8e62af3f/builds/linux/ubuntu/20-04-lts/data/user-data.pkrtpl.hcl#L3

by accident. it just bothered me for no reason :)

### Suggestion

Just remove line 4

**Comment by sepsh** [comment]
PR: #938

**Comment by sepsh** [comment]
![It ain't much, but it's honest work](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExbWI5MGVpbmMwY3puamcycnB3MDRydWxhajIxOHhzNzAybjY2ZnJkaSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/1jCs6Doz3WRtOPl6bq/giphy.webp)

**Comment by tenthirtyam** [comment]
Pulled into ca58cf14169151ae8bcdfc8c0b6c52f4119bcc05.
