### ISSUE TITLE
Update documentation for Machine Images

### ISSUE THREAD

**Issue by alcorwalter** [vmware-samples/packer-examples-for-vsphere#970]
### Code of Conduct

- [X] I have read and agree to the project's Code of Conduct.

### Project Version

develop

### Motivation

Choice to simplify variables and build files (https://github.com/vmware-samples/packer-examples-for-vsphere/pull/944) is not reflected clearly in documentation (https://vmware-samples.github.io/packer-examples-for-vsphere/getting-started/configure/#machine-images).
This can be confusing.

### Suggestion

At the very least, it seems to me that you should indicate that the variables to be used are in the “Machine Images Settings” section of the `builds/<type>/<os>/<version>/variables.pkr.hcl` file.
And if these variables could be dynamically added to the documentation, that would be more didactic.
Especially as this section in the documentation indicates that the example file is `config/linux-photon-5.pkrvars.hcl`, but the variables are for Ubuntu 24.04.

**Comment by tenthirtyam** [comment]
Already addressed in https://github.com/vmware-samples/packer-examples-for-vsphere/pull/948 and ill appear in next docs update.
